### ISSUE TITLE
Move to a strongly type language ?

### ISSUE THREAD

**Issue by maiste** [vch9/PresidentJS#15]
I think that vanilla JS isn't the right language to build our app. We might use another language that compile to javascript. Suggestions:
* PureScript
* Elm
* ReasonML
* Typescript

**Comment by vch9** [comment]
Would have saved me a lot of time if I'd listened to you

**Comment by maiste** [comment]
Yes indeed! You should move to typescript. It's javascript but with type improvement :+1:
