### ISSUE TITLE
Online create/join room implementation

### ISSUE THREAD

**Issue by vch9** [vch9/PresidentJS#7]
The possibility of creating a room and joining one:
* Listing all the currents rooms 
* Listing all the ongoing games ?
* Sending our new room to the server

**Comment by maiste** [comment]
I think we can:
* create a room
* join a room

Maybe, that's all for now. We can at the feature to join unknown rooms later.

**Comment by vch9** [comment]
We could do with a random unique link to the room.  
When the user creates a room he has a link to share.

**Comment by maiste** [comment]
That's ok for me.
